import NFTCardItem from 'components/NFTCardItem'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import useInitMoralis from '../lib/custom-hooks/useInitMoralis'
import styles from '../styles/Home.module.css'

const PageHead = () => (
  <Head>
    <title>NFT Minter</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
)

const Home: NextPage = () => {
  const {
    user,
    nftList,
    handleMint,
    handleMintNewNFT,
    handleSetFile,
  } = useInitMoralis()

  return (
    <div className={styles.container}>
      <PageHead />
      <header>
        {user && (
          <div>{`User: ${user.getUsername()}`}</div>
        )}
      </header>
      <div
        className='flex'
      >
          {nftList.map((n, i) => (
            <NFTCardItem 
              key={i}
              metadata={n.parsedMetadata}
              onMint={handleMint}
            />
          ))}
      </div>
      <div>
        <label>
          {'Upload file for new NFT.'}
          <input 
            type="file"
            onChange={handleSetFile}
          />
        </label>
        <hr />
        <button className="btn btn-primary" onClick={handleMintNewNFT}>
            {'Mint a New NFT!'}
        </button>
      </div>
    </div>
  )
}

export default Home
