import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import useLoginMoralis from '../lib/custom-hooks/useLoginMoralis'
import styles from '../styles/Home.module.css'

const PageHead = () => (
  <Head>
    <title>Create Next App</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
)

const Home: NextPage = () => {
  const {
    user,
  } = useLoginMoralis()
  return (
    <div className={styles.container}>
      <PageHead />
      <header>
        {user && (
          <div>{`User: ${user.getUsername()}`}</div>
        )}
      </header>
      <div>
        
      </div>
    </div>
  )
}

export default Home
