import ApproveUserForm from 'components/ApproveUserForm'
import NFTCardItem from 'components/NFTCardItem'
import TransferNFTForm from 'components/TransferNFTForm'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { Callback } from 'types'
import useInitMoralis from '../lib/custom-hooks/useInitMoralis'
import styles from '../styles/Home.module.css'

const PageHead = () => (
  <Head>
    <title>NFT Minter</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
)

const Home: NextPage = () => {
  const {
    user,
    userAddressRef,
    nftList,
    handleMint,
    handleMintNewNFT,
    handleTransferNFT,
    handleSetFile,
    handleChangeMintInputState,
  } = useInitMoralis()

  return (
    <div className={styles.container}>
      <PageHead />
      <header>
        {user && (
          <div>{`User: ${user.getUsername()}`}</div>
        )}
      </header>
      <hr />
      <div
        className='flex'
      >
          {nftList.map((n, i) => (
            <NFTCardItem 
              key={i}
              commonTokenInfo={n}
              metadata={n.parsedMetadata}
              onMint={handleMint}
            />
          ))}
      </div>
      <hr />
      <h2>Test Transfer</h2>
      <button className="btn btn-primary" onClick={handleTransferNFT}>
        Transfer to my Address
      </button>
      <hr />
      <ApproveUserForm />
      <TransferNFTForm 
        userAddress={userAddressRef}
      />
    </div>
  )
}

export default Home
